                *** program Y:\impg\macros\matrix3.sas         ***;
          *** creates ranks of multifactor model by matrix report ***;
%macro matrix3(year,month);
     %let month=%upcase(&month);
data factor;
     set impg.factor;
          %if &month=OCT %then mooth=10; ;
          %if &month=NOV %then mooth=11; ;
          %if &month=DEC %then mooth=12; ;
          %if &month=JAN %then mooth= 1; ;
          %if &month=FEB %then mooth= 2; ;
          %if &month=MAR %then mooth= 3; ;
          %if &month=APR %then mooth= 4; ;
          %if &month=MAY %then mooth= 5; ;
          %if &month=JUN %then mooth= 6; ;
          %if &month=JUL %then mooth= 7; ;
          %if &month=AUG %then mooth= 8; ;
          %if &month=SEP %then mooth= 9; ;
     if year=&year and month=mooth;

     if divers in ('CG','EG','OG') then div=1;
        else if divers in ('BAS','OPP','UT') then div=2;
              else div=.;

     if f3 > 10 then f3 =10;
     if f3=. then delete;
     keep ticker eco divers div f3 f3l;
     run;
%dup(factor); 
proc means data=factor noprint; 
     output out=all mean= ;
     var f3 f3l;
     run;
data all;
     set all;
     econ=11;
     divn=9;
     title 'all data';
*proc print data=all;
     run;
%macro mea(sort,name);
proc sort data=factor;
     by &sort;
proc means data=factor noprint;
     by &sort;
     output out=&name mean= ;
     var f3 f3l;
     title "&name data";
%if &name=cells2 %then %do;
                       proc sort data=&name ;
                       by div;
                       %end;
proc rank data=&name out=f&name;
     %if &name=cells2 %then %do; BY DIV; %end;
     ranks ranks ranksl;
     var f3 f3l;
*proc print data=f&name;

%mend;
%mea(eco divers,cells);
%mea(eco div,cells2);
%mea(eco,eco);
%mea(divers,divers);
%mea(div,div);
         *** Print report ***;
data final;
     set fcells fcells2 feco fdivers fdiv all;
     if       ECO='CND' then econ=1;
      else if ECO='HC'  then econ=2;
      else if ECO='CGD' then econ=3;
      else if ECO='TEC' then econ=4;
      else if ECO='BMI' then econ=5;
      else if ECO='FIN' then econ=6;
      else if ECO='SER' then econ=7;
      else if ECO='RET' then econ=8;
      else if ECO='EN'  then econ=9;
      else if ECO='UT'  then econ=10;
      else                   econ=11;

     if       DIVERS='CG'  then divn=1;
      else if DIVERS='EG'  then divn=2;
      else if DIVERS='OG'  then divn=3;
      else if DIVERS='BAS' then divn=4;
      else if DIVERS='OPP' then divn=5;
      else if DIVERS='UT'  then divn=6;
      else if DIV   =1     then divn=7;
      else if DIV   =2     then divn=8;
      else                      divn=9;
 /*proc freq ;
     title Beta;
     tables econ*divn /norow nocol nopercent;
     weight beta;
     run;
 */
     title 'IMPG QUANTITATIVE UNIVERSE MULTIFACTOR MODEL BY MATRIX';
options ls=142 ps=60;
data _null_;
     set final end=eof;
     retain e1-e99;
     retain r1-r99;
     retain s1-s99;
     retain z1-z99;
     retain nam1-nam11;
     array eet[9,11] e1-e99;
     array ret[9,11] r1-r99;
     array set[9,11] s1-s99;
     array bet[9,11] z1-z99;
     array nam[11] $24 nam1-nam11;
     file PRINT;
     do i=1 to 9;
        do j=1 to 11;
          if econ=j and divn=i then do;
                                  ret{i,j}=ranks ;
                                  eet{i,j}=ranksl;
                                  set{i,j}=f3  ;
                                  bet{i,j}=f3l ;
                                  end;
          end;
        end;
     if eof then do;
        nam1 =' Consumer Non-Durables';
        nam2 ='            Healthcare';
        nam3 ='Capital Goods Durables';
        nam4 ='            Technology';
        nam5 ='Basic Mat. Intermed Goods';
        nam6 ='             Financial';
        nam7 ='               Service';
        nam8 ='                Retail';
        nam9 ='                Energy';
        nam10='             Utilities';
        nam11='              Subtotal';
       put _page_ ;
        put ;
        put ;
  put
'           Economic                 Cons      Emerg       Other       Basic       Opport        Util      Total       Total ';
  put
'            Sectors   Factors     Growth      Growth      Growth      Comps       -unity      -ities      Growth      Value       Subtotal';
  put
'   ----------------   -------     ------      ------      ------      -----       ------      -------     -------     -----       --------';
       do j=1 to 11;
          put nam{j} ;
          put ;
          put @22 'CURR.SCR' @;
          do i=1 to 9;
            put set{i,j} 9.2 ret{i,j} 3.0 @ ;
            end;
          put ;
          put @22 'PRE. SCR' @;
          do i=1 to 9;
            put bet{i,j} 9.2 eet{i,j} 3.0 @ ;
            end;
          put ;

        end;
        put ;
        PUT ;
        PUT ;
        PUT 'First number is average Factor-3, second number is relative rank';
        PUT _page_;
        end;
    run;
proc sort data=impg.mx2 nodupkey;
     by year month un vv eco divers;
     run;
data mx2;
     merge impg.mx2 factor;
     by year month un vv eco divers;
     run;
 /*
proc print data=cells;run;
     where eco='CND' and divers='OG';
     run;
proc means data=factor;
     where eco='CND' and divers='OG';
     var ddm;
     run;
 */
%mend matrix3;


   %*matrix3(1998,jul);
