                *** program Y:\impg\macros\matrix.sas          ***;
                *** creates multifactor model by matrix report ***;
%macro matrix(year,month);
     %let month=%upcase(&month);
data factor factorl factors;
     set impg.factor;
          %if &month=OCT %then mooth=10; ;
          %if &month=NOV %then mooth=11; ;
          %if &month=DEC %then mooth=12; ;
          %if &month=JAN %then mooth= 1; ;
          %if &month=FEB %then mooth= 2; ;
          %if &month=MAR %then mooth= 3; ;
          %if &month=APR %then mooth= 4; ;
          %if &month=MAY %then mooth= 5; ;
          %if &month=JUN %then mooth= 6; ;
          %if &month=JUL %then mooth= 7; ;
          %if &month=AUG %then mooth= 8; ;
          %if &month=SEP %then mooth= 9; ;
     if year=&year and month=mooth;

     if divers in ('CG','EG','OG') then div=1;
        else if divers in ('BAS','OPP','UT') then div=2;
              else div=.;

     if f3 > 10 then f3 =10;
     if f3l> 10 then f3l=10;
     keep ticker eco divers div name ddm b14d ltrpsd f3 f3l beta mktcap year month;
     output factor;
     if mktcap >= 1000 then output factorl;
     if mktcap <  1000 then output factors;
     run;
%macro univrun(file,UN);
%dup(&file);

proc means data=&file noprint;
     output out=all mean= ;
     var year month ddm b14d ltrpsd f3 f3l beta;
     run;
     title 'all data';
*proc print data=all;
     run;
data &UN(keep=year month eco divers un vv x);
     set all;
     eco='TOT';
     divers='TOT';
     un="&UN" ;
     vv='BETA'; x=beta  ;  output;
     vv='DDM' ; x=DDM   ;  output;
     vv='F3'  ; x=F3    ;  output;
     vv='RS'  ; x=ltrpsd;  output;
     vv='ER'  ; x=b14d  ;  output;
%macro mea(sort,name);
proc sort data=&file;
     by &sort;
proc means data=&file noprint;
     by &sort;
     output out=&name mean= ;
     var year month ddm b14d ltrpsd f3 f3l beta;
     title "&name data";
*proc print data=&name;
data temp(keep=year month eco divers un vv x);
     set &name;
     %if &name=divers %then %do;    eco='TOT'; %end;
     %if &name=div    %then %do;    eco='TOT'; %end;
     %if &name=eco    %then %do; divers='TOT'; %end;
     %if &name=div    %then %do;
                              if div=1 then divers='GR';
                              if div=2 then divers='VL';
                              %end;
     %if &name=cells2 %then %do;
                              if div=1 then divers='GR';
                              if div=2 then divers='VL';
                              %end;
  *  year=0 + &year;
  *  month=0 + &month;
     un="&UN" ;
     vv='BETA'; x=beta  ;  output;
     vv='DDM' ; x=DDM   ;  output;
     vv='F3'  ; x=F3    ;  output;
     vv='RS'  ; x=ltrpsd;  output;
     vv='ER'  ; x=b14d  ;  output;
data &UN;
     set &UN temp;
     run;
%mend;
%mea(eco divers,cells);
%mea(eco div,cells2);
%mea(eco,eco);
%mea(divers,divers);
%mea(div,div);
proc sort data=&UN nodupkey;
     by year month un vv eco divers;
     run;
         *** Print report ***;
data final;
     set cells eco divers all;
     if       ECO='CND' then econ=1;
      else if ECO='HC'  then econ=2;
      else if ECO='CGD' then econ=3;
      else if ECO='TEC' then econ=4;
      else if ECO='BMI' then econ=5;
      else if ECO='FIN' then econ=6;
      else if ECO='SER' then econ=7;
      else if ECO='RET' then econ=8;
      else if ECO='EN'  then econ=9;
      else if ECO='UT'  then econ=10;
      else                   econ=11;

     if       DIVERS='CG'  then divn=1;
      else if DIVERS='EG'  then divn=2;
      else if DIVERS='OG'  then divn=3;
      else if DIVERS='BAS' then divn=5;
      else if DIVERS='OPP' then divn=6;
      else if DIVERS='UT'  then divn=7;
      else                      divn=9;
data final2;
     set cells2 div ;
     if       ECO='CND' then econ=1;
      else if ECO='HC'  then econ=2;
      else if ECO='CGD' then econ=3;
      else if ECO='TEC' then econ=4;
      else if ECO='BMI' then econ=5;
      else if ECO='FIN' then econ=6;
      else if ECO='SER' then econ=7;
      else if ECO='RET' then econ=8;
      else if ECO='EN'  then econ=9;
      else if ECO='UT'  then econ=10;
      else                   econ=11;
     if       DIV=1  then divn=4;
      else if DIV=2  then divn=8;
      else put 'error';
data finall;
     set final final2;
 /*proc freq ;
     title Beta;
     tables econ*divn /norow nocol nopercent;
     weight beta;
     run;
 */
     title 'IMPG QUANTITATIVE UNIVERSE MULTIFACTOR MODEL BY MATRIX';
     title2 "For Universe = &UN and for Date= &month &year";
options ps=95;
data _null_;
     set finall end=eof;
     retain d1-d99;
     retain e1-e99;
     retain r1-r99;
     retain s1-s99;
     retain l1-l99;
     retain z1-z99;
     retain nam1-nam11;
     array det[9,11] d1-d99;
     array eet[9,11] e1-e99;
     array ret[9,11] r1-r99;
     array set[9,11] s1-s99;
     array let[9,11] l1-l99;
     array bet[9,11] z1-z99;
     array nam[11] $24 nam1-nam11;
     file PRINT;
     do i=1 to 9;
        do j=1 to 11;
          if econ=j and divn=i then do;
                                  det{i,j}=ddm ;
                                  eet{i,j}=b14d ;
                                  ret{i,j}=ltrpsd;
                                  set{i,j}=f3  ;
                                  let{i,j}=f3l ;
                                  bet{i,j}=beta;
                                  end;
          end;
        end;
     if eof then do;
        nam1 =' Consumer Non-Durables';
        nam2 ='            Healthcare';
        nam3 ='Capital Goods Durables';
        nam4 ='            Technology';
        nam5 ='Basic Mat. Intermed Goods';
        nam6 ='             Financial';
        nam7 ='               Service';
        nam8 ='                Retail';
        nam9 ='                Energy';
        nam10='             Utilities';
        nam11='              Subtotal';
*       put _page_ ;
        put ;
        put ;
  put '           Economic               Cons    Emerg    Other    Total    Basic    Opport   Util     Total            ';
  put '            Sectors   Factors   Growth   Growth   Growth   Growth    Comps    -unity -ities     Value    Subtotal';
  put '   ----------------   -------   ------   ------   ------   ------    -----    ------ ------     -----    --------';
       do j=1 to 11;
          put nam{j} ;
          put @22 '     DDM' @;
          do i=1 to 9;
            put det{i,j} 9.2 @ ;
            end;
          put ;
          put @22 ' E.E.RVS' @;
          do i=1 to 9;
            put eet{i,j} 9.2 @ ;
            end;
          put ;
          put @22 'REL.STRG' @;
          do i=1 to 9;
            put ret{i,j} 9.2 @ ;
            end;
          put ;
          put @22 'CURR.SCR' @;
          do i=1 to 9;
            put set{i,j} 9.2 @ ;
            end;
          put ;
          put @22 'PRE. SCR' @;
          do i=1 to 9;
            put let{i,j} 9.2 @ ;
            end;
          put ;
          put @22 '    BETA' @;
          do i=1 to 9;
            put bet{i,j} 9.2 @ ;
            end;
          put ;
        end;
        end;
*       put _page_ ;
    run;

%mend univrun;
%univrun(factor,UN);
%univrun(factors,SM);
%univrun(factorl,LG);
proc sort data=impg.mx2 nodupkey;
     by year month un vv eco divers;
     run;
data impg.mx2;
     merge impg.mx2 UN SM LG;
     by year month un vv eco divers;
     run;
/*
proc sort data=app out=out nodupkey;
     by year month un vv eco divers;
     run;
proc print data=app;
     run;
proc means;
     run;
data _null_;
     set impg.mx;
     by year month un vv eco divers;
     if first.divers ne last.divers then put _all_;
     run;
*/
%mend matrix;


   %*matrix(1998,jul);
